Skip to content
This repository
Search
Pull requests
Issues
Marketplace
Explore
 @Usman-Amir
 Sign out
 Watch 1
  Star 0  Fork 0 aajiwani/digi-hr-app
 Code  Issues 0  Pull requests 1  Projects 1  Wiki  Insights
Branch: master Find file Copy pathdigi-hr-app/.travis.yml
2279c44  9 days ago
 JIWA350164 Adds goals to the travis build mechanism
1 contributor
RawBlameHistory     
58 lines (57 sloc)  7.98 KB
language: android
sudo: false
before_install:
- nvm install 6
- node --version
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH
- gem install fastlane
cache:
  yarn: true
install:
- yarn install
jdk:
- oraclejdk8
android:
  components:
  - build-tools-26.0.2
  - android-26
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-23
  - tools
  - platform-tools
  - extra
  licenses:
  - android-sdk-license-.+

